CREATE TABLE IF NOT EXISTS chores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  category TEXT NOT NULL,
  task TEXT NOT NULL,
  chore_name TEXT,
  note TEXT,
  score INTEGER,
  multiplier INTEGER DEFAULT 1,
  multiplier_message TEXT,
  assignee TEXT
);
