import type { Metadata } from "next";
import { Geist, Geist_Mono, Yusei_Magic } from "next/font/google"; // Yusei_Magicを追加
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const yuseiMagic = Yusei_Magic({ // Yusei_Magicを追加
  weight: "400",
  subsets: ["latin"],
  variable: "--font-yusei-magic", // CSS変数名を追加
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yuseiMagic.variable} antialiased`} // yuseiMagic.variableを追加
      >
        {children}
      </body>
    </html>
  );
}
