-- ペット基本情報テーブル
CREATE TABLE pet_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    species TEXT NOT NULL,
    emoji_icon TEXT NOT NULL,
    acquisition_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ペット汎用記録テーブル
CREATE TABLE pet_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT REFERENCES pet_info(id) ON DELETE CASCADE,
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    record_type TEXT NOT NULL,
    numeric_value DECIMAL,
    unit TEXT,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE pet_info IS 'ペットの基本情報';
COMMENT ON TABLE pet_records IS 'ペットの日々の汎用記録';
