-- ペット記録項目（マスター）テーブル
CREATE TABLE IF NOT EXISTS pet_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    unit TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- デフォルトの記録項目を挿入
INSERT INTO pet_items (label, unit, display_order) VALUES
('体重', 'g', 1),
('体長', 'cm', 2),
('水温', '℃', 3),
('気温', '℃', 4),
('日記', '', 5),
('お別れ', '', 6),
('その他', '', 7);

COMMENT ON TABLE pet_items IS 'ペットの記録項目マスター';
