ALTER TABLE chores ADD COLUMN IF NOT EXISTS score INTEGER;
ALTER TABLE chores ADD COLUMN IF NOT EXISTS multiplier INTEGER DEFAULT 1;
ALTER TABLE chores ADD COLUMN IF NOT EXISTS multiplier_message TEXT;
ALTER TABLE chores ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE chores ADD COLUMN IF NOT EXISTS task TEXT;
