-- 1. 既存のテーブルをリネームしてバックアップ
ALTER TABLE chore_tasks RENAME TO chore_tasks_old;

-- 2. 新しいスキーマで chore_tasks テーブルを再作成
CREATE TABLE chore_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id TEXT REFERENCES chore_categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  score INTEGER NOT NULL,
  icon TEXT,
  is_repeatable BOOLEAN DEFAULT FALSE,
  is_bubble BOOLEAN DEFAULT FALSE,
  is_rare BOOLEAN DEFAULT FALSE,
  display_order INTEGER DEFAULT 0,
  -- 複合ユニーク制約を追加して、同じカテゴリ内に同じタスク名が重複しないようにする
  UNIQUE (category_id, name)
);

-- 3. 古いテーブルから新しいテーブルへデータを移行
-- 古いIDの順序をある程度維持するため、IDのテキストをソートキーにする
INSERT INTO chore_tasks (category_id, name, score, icon, is_repeatable, is_bubble, is_rare, display_order)
SELECT category_id, name, score, icon, is_repeatable, is_bubble, is_rare, display_order
FROM chore_tasks_old
ORDER BY id;

-- 4. 古いテーブルを削除
DROP TABLE chore_tasks_old;
